# Copyright 2022 Ben Woodward. All rights reserved.
# Use of this source code is governed by a GPL style
# license that can be found in the LICENSE file.
title = "Matteo takes Photos"
baseURL = "https://matdz.github.io"
languageCode = "en-us"
paginate = 30
paginatePath = ""
[permalinks]
  img = "/img/:title/"
